### ISSUE TITLE
ARC

### ISSUE THREAD

**Issue by bayfatih2000** [inamiy/YISplashScreen#3]
Can I use with ARC project?

**Comment by inamiy** [comment]
Yes. This library requires ARC.

**Comment by inamiy** [comment]
This library also requires QuartzCore framework.
You can just `#import <QuartzCore/QuartzCore.h>` to your .pch file,
or try 066249d which I fixed just now.

**Comment by bayfatih2000** [comment]
It is Ok. My project uses navigation controller and storyboard. I change Default.png but it uses old png file (black screen). How can I solve this problem. Thank you

**Comment by inamiy** [comment]
Do you mean you have default-black `Default.png` and your custom splash image at same project?

Actually, current version uses either `Default.png` or `Default-568h.png` image as a splash image,
so you should either rename your custom one to `Default.png`, or straightly change the code in line 38-43 to whatever imageName you want.

And yes, it may be necessary to add `-setSplashImageName:` feature in future... I will note it :)

**Comment by bayfatih2000** [comment]
I added Default@2x and Derfault-568h@2x. It is Ok. Thank you very much.
