### ISSUE TITLE
Not showing view from storyboard

### ISSUE THREAD

**Issue by Tim-Kindberg** [inamiy/YISplashScreen#6]
Hi,

I call [YISplashScreen show] in didFinishLaunchingWithOptions but don't call [YISplashScreen hide] until my UIWebView has loaded - which my ViewController finds out about later.

Except that my ViewController (created via a storyboard) doesn't load. Looking at your code, it seems that your fix for the following issue: 

https://github.com/inamiy/YISplashScreen/issues/4

... has caused this.

If I put the call to [YISplashScreen hide] after [YISplashScreen show] in didFinishLaunchingWithOptions then my view controller loads. But I need my hide to be under programmatic control as indicated.

Thanks,

Tim

**Comment by inamiy** [comment]
Hi, thanks for feedback :)

Can you try a96d19e? I hope this will work.

**Comment by Tim-Kindberg** [comment]
Hi,

Thanks. That takes me further: the splash screen now remains until the 
right time. However, when the underlying interface elements appear, (1) 
a short video I play to begin with on top of (and launched from) my 
UIWebView doesn't appear at all, and (2) my UIWebView has switched to 
portrait mode even though it was locked to landscape in the xcode 
Summary page.

When I put [YISplashScreen hide] back to immediately after the call to 
show, everything is fine in those respects.

I appreciate your help in resolving this.

Best wishes,

Tim

On 09/07/2013 09:29, Yasuhiro Inami wrote:

> Hi, thanks for feedback :)
> 
> Can you try a96d19e 
> https://github.com/inamiy/YISplashScreen/commit/a96d19e? I hope this 
> will work.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/inamiy/YISplashScreen/issues/6#issuecomment-20660064.

## 

Tim Kindberg
matter 2 media Ltd and Pervasive Media Studio
w: matter2media.com
e: tim@matter2media.com
m: +44 (0)7954 582814
t: +44 (0)117 9095221

**Comment by inamiy** [comment]
Hmm... I couldn't figure out the situation.
Can you send me a demo for this issue?

(BTW I tried UIWebView + youtube URL test in my local working copy, but it worked fine)

**Comment by inamiy** [comment]
Can't reproduce the issue so far, so I will close here.
